# Generated by Django 5.0.7 on 2024-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='clases_inscritas',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='api.clase'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='clases_impartidas',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='api.clase'),
        ),
    ]
